env: # Environment type {development}, {production}, ...
accessToken: # Access Token for JSON Web Token, should be really secure
dsn: # DSN for connecting to SQL Database
port: # Server Port should be like ":3000" (Do not remove the double quotes)
loginAttemptsLimit: # Login attempts limit, just a number 4, 5, ...
loginAttemptsDuration: # Login attempts duration (in minutes)
rateLimit: # General Rate limit
rateDuration: # rate limit duration (in seconds)
