env: development
accessToken: 69zDfhhZUxnNl63VqmV3EQWja9++RsqORbltMyeTMVHm
dsn: ahmad:password@/jasad?parseTime=true
port: ":3000"
loginAttemptsLimit: 5
loginAttemptsDuration: 5 # in minutes
rateLimit: 10
rateDuration: 30 # in seconds
